### ISSUE TITLE
Default directory for the file chooser can not exist on some cases

### ISSUE THREAD

**Issue by flvinny** [rhmodding/Treasury#3]
The file chooser in Treasury assumes that the user's Desktop folder is located at ``C:\Users\[user]\Desktop``. This is not always the case, as it's possible for a user to move said folder to somewhere else. 
https://www.windowscentral.com/how-move-default-user-folders-new-drive-windows-10

I recently re-formatted my computer, so I could keep one partition for system files and another for my personal files. I've moved my Desktop folder to ``D:\Desktop`` and as such, Treasury spits an error (the same as the one on #2 ) instead of opening the file chooser.

**Comment by chrislo27** [comment]
Resolved as of commit b0b0489171f18a26ba5f56ca5a439f055cb69aba, default zlib directory will now be just the user home. Patch will be issued later today.
